server:
  port: 80
  servlet:
    context-path: /
#配置视图解析器
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .html
    date-format: yyyy-MM-dd
  redis:
    host: 127.0.0.1
    port: 6379


  #数据源：spring自带的数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10

#分页配置
pagehelper:
  reasonable: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名法
    use-generated-keys: true  #获取自增主键值
    use-column-label: true #替换列别名